// apps/web/src/components/prompt/PromptMonacoEditor.tsx
import Editor, { loader } from '@monaco-editor/react';
import * as monaco from 'monaco-editor';
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';

// 使用本地打包的 monaco，避免默认从 CDN 加载，保证离线部署可用。
window.MonacoEnvironment = {
  getWorker() {
    return new EditorWorker();
  }
};

loader.config({ monaco });

interface PromptMonacoEditorProps {
  value: string;
  onChange?: (value: string) => void;
  language?: string;
  readOnly?: boolean;
}

export function PromptMonacoEditor({
  value,
  onChange,
  language = 'markdown',
  readOnly = false
}: PromptMonacoEditorProps) {
  return (
    <div className="monaco-host">
      <Editor
        value={value}
        language={language}
        height="100%"
        onChange={(next) => onChange?.(next ?? '')}
        options={{
          readOnly,
          automaticLayout: true,
          minimap: { enabled: false },
          scrollBeyondLastLine: false,
          wordWrap: 'on',
          fontSize: 14,
          lineHeight: 22,
          padding: { top: 16, bottom: 16 },
          renderLineHighlight: 'line',
          scrollbar: {
            verticalScrollbarSize: 10,
            horizontalScrollbarSize: 10
          }
        }}
      />
    </div>
  );
}

// apps/web/src/components/prompt/PromptMonacoEditor.vue
<template>
  <div ref="containerRef" class="monaco-host" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

const props = withDefaults(
  defineProps<{
    modelValue: string;
    language?: string;
    readOnly?: boolean;
  }>(),
  {
    language: 'markdown',
    readOnly: false
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const containerRef = ref<HTMLElement>();
let editor: monaco.editor.IStandaloneCodeEditor | undefined;

window.MonacoEnvironment = {
  getWorker() {
    return new editorWorker();
  }
};

onMounted(() => {
  if (!containerRef.value) {
    return;
  }

  editor = monaco.editor.create(containerRef.value, {
    value: props.modelValue,
    language: props.language,
    readOnly: props.readOnly,
    automaticLayout: true,
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
    wordWrap: 'on',
    fontSize: 14,
    lineHeight: 22,
    padding: { top: 16, bottom: 16 },
    renderLineHighlight: 'line',
    scrollbar: {
      verticalScrollbarSize: 10,
      horizontalScrollbarSize: 10
    }
  });

  editor.onDidChangeModelContent(() => {
    const value = editor?.getValue() ?? '';
    if (value !== props.modelValue) {
      emit('update:modelValue', value);
    }
  });
});

watch(
  () => props.modelValue,
  (value) => {
    if (editor && value !== editor.getValue()) {
      editor.setValue(value);
    }
  }
);

watch(
  () => props.readOnly,
  (value) => {
    editor?.updateOptions({ readOnly: value });
  }
);

onBeforeUnmount(() => {
  editor?.dispose();
});
</script>
