// apps/web/src/components/layout/AppLayout.vue
<template>
  <div class="app-shell">
    <header class="app-topbar">
      <RouterLink class="brand" to="/prompts">
        <span class="brand-mark">
          <Boxes class="h-4 w-4" />
        </span>
        <span>Prompt Skill Manager</span>
      </RouterLink>

      <div class="topbar-actions">
        <Button variant="ghost" size="icon">
          <Search class="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon">
          <Bell class="h-4 w-4" />
        </Button>
        <span class="admin-badge">
          <CircleUserRound class="h-4 w-4" />
          Admin
        </span>
      </div>
    </header>

    <aside class="app-sidebar">
      <nav class="nav-section">
        <RouterLink
          v-for="item in primaryNav"
          :key="item.key"
          :class="['nav-link', { active: isPrimaryActive(item) }]"
          :to="item.to"
        >
          <component :is="item.icon" class="h-4 w-4" />
          <span>{{ item.label }}</span>
        </RouterLink>
      </nav>

      <div class="nav-title">管理</div>
      <nav class="nav-section">
        <RouterLink
          v-for="item in manageNav"
          :key="item.path"
          :class="['nav-link', { active: isManageActive(item.path) }]"
          :to="item.path"
        >
          <component :is="item.icon" class="h-4 w-4" />
          <span>{{ item.label }}</span>
        </RouterLink>
      </nav>
    </aside>

    <main class="app-main">
      <RouterLink
        v-if="backTarget"
        class="app-main-back"
        :to="backTarget"
        title="返回上级"
        aria-label="返回上级"
      >
        <ArrowLeft class="h-4 w-4" />
      </RouterLink>
      <RouterView />
    </main>

    <Toaster />
    <ConfirmDialog />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { RouterLink, RouterView, useRoute } from 'vue-router';
import {
  ArrowLeft,
  Bell,
  Boxes,
  CircleUserRound,
  Folder,
  House,
  Lightbulb,
  Tags,
  Search,
  Star
} from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import ConfirmDialog from '@/components/ui/confirm/ConfirmDialog.vue';
import Toaster from '@/components/ui/toast/Toaster.vue';

const route = useRoute();

const primaryNav = [
  { key: 'prompts', label: 'Prompt 列表', to: '/prompts', icon: House },
  { key: 'favorites', label: '我的收藏', to: { path: '/prompts', query: { favorite: 'true' } }, icon: Star },
  { key: 'solutions', label: '解决方案', to: '/solutions', icon: Lightbulb }
];

const manageNav = [
  { label: '分类管理', path: '/categories', icon: Folder },
  { label: '标签管理', path: '/tags', icon: Tags }
];

const normalizedPath = computed(() => route.path);

const backTarget = computed(() => {
  if (route.name === 'prompt-detail') return '/prompts';
  if (route.name === 'solution-detail') return '/solutions';
  return '';
});

function isPrimaryActive(item: (typeof primaryNav)[number]) {
  if (item.key === 'favorites') {
    return normalizedPath.value === '/prompts' && route.query.favorite === 'true';
  }

  if (item.key === 'prompts') {
    return normalizedPath.value.startsWith('/prompts') && route.query.favorite !== 'true';
  }

  if (item.key === 'solutions') {
    return normalizedPath.value.startsWith('/solutions');
  }

  return false;
}

function isManageActive(path: string) {
  return normalizedPath.value === path;
}
</script>

// apps/web/src/components/layout/AppLayout.tsx
import { type ComponentType } from 'react';
import { Link, Outlet, useLocation } from 'react-router-dom';
import {
  ArrowLeft,
  Bell,
  Boxes,
  CircleUserRound,
  Folder,
  House,
  Lightbulb,
  type LucideProps,
  Search,
  Star,
  Tags
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

type IconComponent = ComponentType<LucideProps>;

interface PrimaryNavItem {
  key: 'prompts' | 'favorites' | 'solutions';
  label: string;
  to: string;
  icon: IconComponent;
}

interface ManageNavItem {
  label: string;
  path: string;
  icon: IconComponent;
}

const primaryNav: PrimaryNavItem[] = [
  { key: 'prompts', label: 'Prompt 列表', to: '/prompts', icon: House },
  { key: 'favorites', label: '我的收藏', to: '/prompts?favorite=true', icon: Star },
  { key: 'solutions', label: '解决方案', to: '/solutions', icon: Lightbulb }
];

const manageNav: ManageNavItem[] = [
  { label: '分类管理', path: '/categories', icon: Folder },
  { label: '标签管理', path: '/tags', icon: Tags }
];

export function AppLayout() {
  const location = useLocation();
  const pathname = location.pathname;
  const favorite = new URLSearchParams(location.search).get('favorite');

  const isPrimaryActive = (item: PrimaryNavItem) => {
    if (item.key === 'favorites') {
      return pathname === '/prompts' && favorite === 'true';
    }
    if (item.key === 'prompts') {
      return pathname.startsWith('/prompts') && favorite !== 'true';
    }
    if (item.key === 'solutions') {
      return pathname.startsWith('/solutions');
    }
    return false;
  };

  const isPromptDetail = /^\/prompts\/(?!new$)[^/]+$/.test(pathname);
  const isSolutionDetail = /^\/solutions\/(?!new$)[^/]+$/.test(pathname);
  const backTarget = isPromptDetail ? '/prompts' : isSolutionDetail ? '/solutions' : '';

  return (
    <div className="app-shell">
      <header className="app-topbar">
        <Link className="brand" to="/prompts">
          <span className="brand-mark">
            <Boxes className="h-4 w-4" />
          </span>
          <span>Prompt Skill Manager</span>
        </Link>

        <div className="topbar-actions">
          <Button variant="ghost" size="icon">
            <Search className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon">
            <Bell className="h-4 w-4" />
          </Button>
          <span className="admin-badge">
            <CircleUserRound className="h-4 w-4" />
            Admin
          </span>
        </div>
      </header>

      <aside className="app-sidebar">
        <nav className="nav-section">
          {primaryNav.map((item) => {
            const Icon = item.icon;
            return (
              <Link
                key={item.key}
                className={cn('nav-link', isPrimaryActive(item) && 'active')}
                to={item.to}
              >
                <Icon className="h-4 w-4" />
                <span>{item.label}</span>
              </Link>
            );
          })}
        </nav>

        <div className="nav-title">管理</div>
        <nav className="nav-section">
          {manageNav.map((item) => {
            const Icon = item.icon;
            return (
              <Link
                key={item.path}
                className={cn('nav-link', pathname === item.path && 'active')}
                to={item.path}
              >
                <Icon className="h-4 w-4" />
                <span>{item.label}</span>
              </Link>
            );
          })}
        </nav>
      </aside>

      <main className="app-main">
        {backTarget ? (
          <Link className="app-main-back" to={backTarget} title="返回上级" aria-label="返回上级">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        ) : null}
        <Outlet />
      </main>

      <Toaster />
      <ConfirmDialog />
    </div>
  );
}
